name: Playwright Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Playwright Test Suite

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧪 Run Playwright tests
        run: npx playwright test

      - name: 📤 Upload JSON and HTML reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: |
            test-results/
            playwright-report/

      - name: 📣 Send summary to Discord
        if: always()
        run: |
          STATUS="${{ job.status }}"
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          RUN_URL="https://github.com/Ariadna-Garcia/Fichap-Playwright/actions/runs/${{ github.run_id }}"

          curl -H "Content-Type: application/json" \
            -X POST ${{ secrets.DISCORD_WEBHOOK }} \
            -d "{
              \"username\": \"CI Reporter\",
              \"avatar_url\": \"https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png\",
              \"embeds\": [{
                \"title\": \"📋 Playwright Test Run - $STATUS\",
                \"url\": \"$RUN_URL\",
                \"color\": ${STATUS^^} == 'SUCCESS' && 3066993 || 15158332,
                \"fields\": [
                  {\"name\": \"Repo\", \"value\": \"Ariadna-Garcia/Fichap-Playwright\", \"inline\": true},
                  {\"name\": \"Branch\", \"value\": \"main\", \"inline\": true},
                  {\"name\": \"Commit\", \"value\": \"${COMMIT_MESSAGE}\"},
                  {\"name\": \"📊 Report\", \"value\": \"[Ver artefacto HTML](https://github.com/Ariadna-Garcia/Fichap-Playwright/actions/runs/${{ github.run_id }})\"}
                ],
                \"timestamp\": \"$(date --iso-8601=seconds)\"
              }]
            }"
